# Generated by Django 2.2.10 on 2020-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_auto_20200419_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='blue', max_length=10),
            preserve_default=False,
        ),
    ]
