# Generated by Django 2.2.10 on 2020-04-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0003_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='plate/%Y/%m/%d')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plate.Plate')),
            ],
        ),
    ]
