# Generated by Django 2.2.10 on 2020-04-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0004_plateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plateimage',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plate.Plate'),
        ),
    ]
